### ISSUE TITLE
replace /usr/bin/terraform? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL

### ISSUE THREAD

**Issue by FernandoMiguel** [clowdhaus/terraform-composite-actions#17]
**Describe the bug**
this action seems to fail deleting terraform binary

**To Reproduce**
githubactions
```
      - name: Pre-commit Terraform
        uses: clowdhaus/terraform-composite-actions/pre-commit@v1.8.3
        with:
          terraform-version: "1.3.6"
          terraform-docs-version: ${{ env.TERRAFORM_DOCS_VERSION }}
          tflint-version: ${{ env.TFLINT_VERSION }}
```

**Expected behavior**
for the install to work from a temp folder

**Screenshots**
![image](https://user-images.githubusercontent.com/168366/206246025-041c8786-3113-45b9-a64b-971926681f12.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 20

**Additional context**
githubactions
